datasets:
  dataset: 'vqa-v2' # 'gqa', 'vqa-v2'
  gqa_dataset_split: 'val'
  gqa_images_dir: '/tmp/datasets/gqa/images'
  gqa_val_questions_file: '/tmp/datasets/gqa/val_balanced_questions.json'
  gqa_val_subset_questions_file: '/tmp/datasets/gqa/gqasubset1000.json'
  gqa_test_questions_file: '/tmp/datasets/gqa/testdev_balanced_questions.json'
  vqa_v2_dataset_split: 'rest-val'  # 'val', 'val1000', 'rest-val', 'test-dev', 'test'
  vqa_v2_val_images_dir: '/tmp/datasets/coco/val2014'
  vqa_v2_val_questions_file: '/tmp/datasets/coco/vqa/v2_OpenEnded_mscoco_val2014_questions.json'
  vqa_v2_val_annotations_file: '/tmp/datasets/coco/vqa/v2_mscoco_val2014_annotations.json'
  vqa_v2_val1000_questions_file: '/tmp/datasets/coco/vqa/v2_OpenEnded_mscoco_val2014_1000subset_questions.json'
  vqa_v2_val1000_annotations_file: '/tmp/datasets/coco/vqa/v2_mscoco_val2014_1000subset_annotations.json'
  vqa_v2_rest_val_questions_file: '/tmp/datasets/coco/vqa/v2_OpenEnded_mscoco_rest_val2014_questions.json'
  vqa_v2_rest_val_annotations_file: '/tmp/datasets/coco/vqa/v2_mscoco_rest_val2014_annotations.json'
  vqa_v2_test_images_dir: '/tmp/datasets/coco/test2015'
  vqa_v2_test_questions_file: '/tmp/datasets/coco/vqa/v2_OpenEnded_mscoco_test2015_questions.json'
  vqa_v2_test_dev_questions_file: '/tmp/datasets/coco/vqa/v2_OpenEnded_mscoco_test-dev2015_questions.json'
  vqa_v2_answer_list: '/tmp/datasets/coco/vqa/answer_list.json'
  percent_test: 1 #0.01
  num_test_data: 10
  use_num_test_data: False
sam:
  GROUNDING_DINO_CONFIG_PATH: "Grounded-Segment-Anything/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
  GROUNDING_DINO_CHECKPOINT_PATH: "Grounded-Segment-Anything/groundingdino_swint_ogc.pth"
  SAM_ENCODER_VERSION: "vit_h"
  SAM_CHECKPOINT_PATH: "Grounded-Segment-Anything/sam_vit_h_4b8939.pth"
  BOX_THRESHOLD: 0.25
  TEXT_THRESHOLD: 0.25
  NMS_THRESHOLD: 0.8
  min_mask_region_area: 1024
  pred_iou_thresh: 0.9
  stability_score_thresh: 0.98
dino:
  GROUNDING_DINO_CONFIG_PATH: "Grounded-Segment-Anything/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
  GROUNDING_DINO_CHECKPOINT_PATH: "Grounded-Segment-Anything/groundingdino_swint_ogc.pth"
  BOX_THRESHOLD: 0.35
  TEXT_THRESHOLD: 0.25
llm:
  llm_model: 'gpt-3.5-turbo'
vlm:
  min_bbox_size: 32
inference:
  verbose: False
  find_nearby_objects: False
  force_multi_agents: False
  nearby_bbox_iou_threshold: 0.5
  print_every: 20
  output_response_filename: 'outputs/responses4_feb21.json'
  save_output_response: True