datasets:
  dataset: 'vqa-v2' # 'gqa', 'vqa-v2'
  gqa_images_dir: '/tmp/datasets/gqa/images'
  gqa_questions_file: '/tmp/datasets/gqa/testdev_balanced_questions.json'
  vqa_v2_dataset_split: 'val'
  vqa_v2_val_images_dir: '/tmp/datasets/coco/val2014'
  vqa_v2_val_questions_file: '/tmp/datasets/vqa-v2/v2_OpenEnded_mscoco_val2014_questions.json'
  vqa_v2_val_annotations_file: '/tmp/datasets/vqa-v2/v2_mscoco_val2014_annotations.json'
  vqa_v2_test_images_dir: '/tmp/datasets/coco/test2015'
  vqa_v2_test_questions_file: '/tmp/datasets/vqa-v2/v2_OpenEnded_mscoco_test2015_questions.json'
  vqa_v2_test_dev_questions_file: '/tmp/datasets/vqa-v2/v2_OpenEnded_mscoco_test-dev2015_questions.json'
  vqa_v2_answer_list: '/tmp/datasets/vqa-v2/answer_list.json'
  percent_test: 0.01
  num_test_data: 1000
  use_num_test_data: True
sam:
  GROUNDING_DINO_CONFIG_PATH: "Grounded-Segment-Anything/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
  GROUNDING_DINO_CHECKPOINT_PATH: "Grounded-Segment-Anything/groundingdino_swint_ogc.pth"
  SAM_ENCODER_VERSION: "vit_h"
  SAM_CHECKPOINT_PATH: "Grounded-Segment-Anything/sam_vit_h_4b8939.pth"
  BOX_THRESHOLD: 0.25
  TEXT_THRESHOLD: 0.25
  NMS_THRESHOLD: 0.8
  min_mask_region_area: 1024
  pred_iou_thresh: 0.9
  stability_score_thresh: 0.98
dino:
  GROUNDING_DINO_CONFIG_PATH: "Grounded-Segment-Anything/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
  GROUNDING_DINO_CHECKPOINT_PATH: "Grounded-Segment-Anything/groundingdino_swint_ogc.pth"
  BOX_THRESHOLD: 0.35
  TEXT_THRESHOLD: 0.25
llm:
  llm_model: 'gpt-3.5-turbo'
vlm:
  min_bbox_size: 32
inference:
  verbose: False
  find_nearby_objects: False
  nearby_bbox_iou_threshold: 0.5
  print_every: 50